.\" Copyright (c) 2011 Edd Barrett <vext01@gmail.com>
.\" Copyright (c) 2011 Martin Ellis <ellism88@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" [[[[[ DONT FORGET TO BUMP THE DATE WHEN YOU MAKE AMMENDMENTS ]]]]]
.\"
.Dd May 16, 2011
.Dt HGD-PROTO 1
.Os
.Sh NAME
.Nm hgd-admin
.Nd HGD protocol specification
.Sh DESCRIPTION
.Nm
is a comprehensive guide to the Hackathon Gunther Daemon protocol. The guide is
provided so as to encourage the implementation new client programs.
.Sh PROTOCOL FUNDAMENTALS
The HGD protocol is a simple mixed text/binary network protocol for use with
.Xr hgd-netd 1
.
The majority of Communications are performed in a turn based fashion
between the server and client. All non-binary communications are line based and terminated
with a carriage return and line feed, so as to remain telnet compatible.
.Pp
Communications start with the server
reporting it's version. the session then continues as follows:
.Bl -enum
.It
Client sends a command and optionally arguments.
.It
Server sends a reply indicating success/failure and optionally some data.
.It
Goto 1.
.El
.Pp
There are two types of reply a client can expect:
.Bl -bullet
.It
Single line replies.
.It
Multi line replies.
.El
.Pp
Clients must be aware which commands return which kind of reply.
.Pp
A server reply may contain multiple items of data, which are separated by the
pipe character, '|'.
.Pp
Arguments are separated by the pipe character, '|'.
.Sh PROTOCOL COMMANDS
.Sh TYPICAL SESSION
